language: python
cache: pip
python: "3.7"
notifications:
  email: false
before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
install:
  - poetry install
script:
  - pytest
before_deploy:
  - cd docs && make html
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: docs/build/html
    skip_cleanup: true
    on:
      branch: master