language: python
cache: pip
python:
- '3.6'
notifications:
  email: false
before_install:
  - pip install pytest
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
