language: python
cache: pip
python:
  - "3.8"
  - "3.7"
  - "3.6"
notifications:
  email: false
before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
install:
  - poetry install
script:
  - pytest